services:
  # База данных
  bd:
    image: postgres:15
    env_file:
      - ./bd/.env
    ports:
      - "5432:5432"
    volumes:
      - bd_data:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # - ~/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  # Бэкенд для авторизации и обмена сообщениями между фронтом, бэкендом и ллм-сервисом
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - bd
    ports:
      - "3001:3001"
    restart: unless-stopped

  # Фронтенд для взаимодействия с пользователем
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Ллм-сервис саммаризации сообщений
  moderator:
    build:
      context: ./moderator
    env_file:
      - ./moderator/.env
    depends_on:
      - backend
    ports:
      - "4000:4000"
    restart: unless-stopped

  # Вспомогательная админка для удобной работы с базой данных
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./bd/.env
    depends_on:
      - bd

  # Сервис мониторинга
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ~/prometheus.yml:/etc/prometheus/prometheus.yml

  # Сервис визуализации
  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      # - ~/monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  bd_data:
  grafana_data: